### ISSUE TITLE
Enable MonetizationLimitCheck policy for apigee edge

### ISSUE THREAD

**Issue by himanshunag** [apigee/apigeelint#379] opened 2023-08-28 09:56 UTC
Currently proxies and shareflows are failing in linting if MonetizationLimitCheck policy is being used and deployment is suppose to happen in the apigee edge. This is to make changes to policymatadata.json file to include Apigee edge profile for MonetizationLimitCheck policy.

**Comment by ssvaidyanathan** [comment] 2023-08-28 15:20
Fixed and released in v2.40.0
Pls reopen if the issue is not fixed with the latest version

**Closed by ssvaidyanathan** 2023-08-28 15:20 UTC
